### ISSUE TITLE
Notify when sending issue in review or functional review with no feature env

### ISSUE THREAD

**Issue by rchampourlier** [jobteaser/job_tomate#44]
- If an issue is moved to review or functional review
- And the issue's field for feature env is empty
- Notify the developer

**Comment by rchampourlier** [comment]
Not sure this is still necessary. Closing it. @marinados feel free to reopen it if it's still useful.

**Comment by marinados** [comment]
probably not! i'll try to see if there's something else i could have time to do on JobTomate, I had a couple of ideas (especially with unassignment of a perfectly assigned to-do task when transitioning into In Dev)
